//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MVC0705DBEntities : DbContext
    {
        public MVC0705DBEntities()
            : base("name=MVC0705DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<student> students { get; set; }
        public DbSet<tblproduct> tblproducts { get; set; }
    
        public virtual ObjectResult<spCheckLogin_Result> spCheckLogin(string ecode, string pass)
        {
            var ecodeParameter = ecode != null ?
                new ObjectParameter("ecode", ecode) :
                new ObjectParameter("ecode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCheckLogin_Result>("spCheckLogin", ecodeParameter, passParameter);
        }
    }
}
