//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public Nullable<double> rate { get; set; }
        public string description { get; set; }
        public string photos { get; set; }
    }
}
